#
# Makefile.mingw
#
# Description: activity compilation for win32
#

ACTIVITY = click_on_letter-activity
ACTIVITY_C_SRC =	\
	click_on_letter.c \


GCOMPRIS_TOP :=		../..
include $(GCOMPRIS_TOP)/global_win32_activity.mak

