#
# Makefile.mingw
#
# Description: activity compilation for win32
#

ACTIVITY = magic_hat_minus-activity
ACTIVITY_C_SRC =	\
	magic_hat.c \


GCOMPRIS_TOP :=		../..
include $(GCOMPRIS_TOP)/global_win32_activity.mak

