#!/bin/bash
#
# Copyright (C) 2002 Bruno Coudoin
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
#######################################################################
#
# This script creates the distribution files for the sounds.
# A package is created by locale
# The version numbering is managed using a tag file VERSION found in sounds/<locale>/VERSION
# It much be run with the list of locale sound dist to create like:
# create_dist_sounds fr en de
# A simpler way is to run:
# make dist-sounds
#

for locale in $@
do
  if test -d boards/sounds/$locale; then 
    if ! test -f boards/sounds/$locale/VERSION; then
	echo ERROR : VERSION File not found in boards/sounds/$locale/
	exit
    fi
    version=`cat boards/sounds/$locale/VERSION`
    echo Creating gcompris-sounds-$locale-$version.tgz
    tar czf gcompris-sounds-$locale-$version.tgz boards/sounds/$locale
  fi
done