#!/bin/sh

echo "Gcompris modified gnome-autogen.sh"

GNOME_COMMON_DATADIR="$BUILD_PATH"
GNOME_COMMON_MACROS_DIR="$BUILD_PATH/gnome2-macros"

export GNOME_COMMON_DATADIR
export GNOME_COMMON_MACROS_DIR

ACLOCAL_FLAGS="-I $GNOME_COMMON_MACROS_DIR $ACLOCAL_FLAGS"
export ACLOCAL_FLAGS

. $GNOME_COMMON_MACROS_DIR/autogen.sh

