/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#include "gcompris/gcompris.h"

void create_mainwindow (GooCanvasItem *rootitem);
GtkWidget* create_fileselectwindow (void);
GtkWidget* create_colorselectwindow (void);
GtkWidget* create_aboutwindow (void);
GtkWidget* create_helpwindow (void);
