#
# Makefile.mingw
#
# Description: activity compilation for win32
#

ACTIVITY = money-activity
ACTIVITY_C_SRC =	\
	money.c \
	money_widget.c \


GCOMPRIS_TOP :=		../..
include $(GCOMPRIS_TOP)/global_win32_activity.mak

