#
# Makefile.mingw
#
# Description: activity compilation for win32
#

ACTIVITY = chess_computer-activity
ACTIVITY_C_SRC =	\
	chess.c \
	chess_notation.c \
	chess_position.c \


GCOMPRIS_TOP :=		../..
include $(GCOMPRIS_TOP)/global_win32_activity.mak

