#
# Makefile.mingw
#
# Description: activity compilation for win32
#

ACTIVITY = canal_lock-activity
ACTIVITY_C_SRC =	\
	canal_lock.c \


GCOMPRIS_TOP :=		../..
include $(GCOMPRIS_TOP)/global_win32_activity.mak

