#
# Makefile.mingw
#
# Description: activity compilation for win32
#

ACTIVITY = advanced_colors-activity
ACTIVITY_C_SRC =	\
	advanced_colors.c \


GCOMPRIS_TOP :=		../..
include $(GCOMPRIS_TOP)/global_win32_activity.mak

