#
# Makefile.mingw
#
# Description: activity compilation for win32
#

ACTIVITY = algebra_by-activity
ACTIVITY_C_SRC =	\
	algebra.c \


GCOMPRIS_TOP :=		../..
include $(GCOMPRIS_TOP)/global_win32_activity.mak

