#
# Makefile.mingw
#
# Description: activity compilation for win32
#

ACTIVITY = fifteen-activity
ACTIVITY_C_SRC =	\
	fifteen.c \


GCOMPRIS_TOP :=		../..
include $(GCOMPRIS_TOP)/global_win32_activity.mak

