#
# Makefile.mingw
#
# Description: activity compilation for win32
#

ACTIVITY = hanoi-activity
ACTIVITY_C_SRC =	\
	hanoi.c \


GCOMPRIS_TOP :=		../..
include $(GCOMPRIS_TOP)/global_win32_activity.mak

