#
# Makefile.mingw
#
# Description: activity compilation for win32
#

ACTIVITY = enumerate-activity
ACTIVITY_C_SRC =	\
	enumerate.c \


GCOMPRIS_TOP :=		../..
include $(GCOMPRIS_TOP)/global_win32_activity.mak

