#
# Makefile.mingw
#
# Description: activity compilation for win32
#

ACTIVITY = awele-activity
ACTIVITY_C_SRC =	\
	awele_alphaBeta.c \
	awele.c \
	awele_utils.c \


GCOMPRIS_TOP :=		../..
include $(GCOMPRIS_TOP)/global_win32_activity.mak

