#!/bin/sh
echo "$0" "$@"

# arguments are unordered, have to loop
args=""
while [ -n "$2" ] ; do
    args="$args $1 $2"
    case "$1" in
      	bundle_id)   bundle_id="$2" ;;
      	activity_id) activity_id="$2" ;;
      	pservice_id) pservice_id="$2" ;;
      	object_id)   object_id="$2" ;;
	uri)         uri="$2" ;;
	*) echo unknown argument $1 $2 ;;
    esac
    shift;shift
done

# really need bundle id and activity id
if [ -z "$bundle_id" -o -z "$activity_id" ] ; then
  echo ERROR: bundle_id and activity_id arguments required
  echo Aborting
  exit 1
fi

# some debug output
echo launching $bundle_id instance $activity_id
[ -n "$pservice_id" ] && echo shared as $pservice_id
[ -n "$object_id"   ] && echo with journal obj $obj_id
[ -n "$uri"         ] && echo loading uri $uri

# now run GCompris startup script
exec $SUGAR_BUNDLE_PATH/runit.sh \
    --sugarBundleId $bundle_id \
    --sugarActivityId $activity_id \
    $args

