#!/bin/sh
export SUGAR_BUNDLE_PATH=`dirname $0`

[ -z "$SUGAR_PROFILE" ] && SUGAR_PROFILE=default
logdir="$HOME/.sugar/$SUGAR_PROFILE/logs"
[ ! -d "$logdir" ] && mkdir -p "$logdir"
log="$logdir/GCompris.log"

echo Started "$0" "$@" >> "$log"

export PATH=$SUGAR_BUNDLE_PATH:$PATH
exec sugar-native-factory "$@" >> "$log" 2>&1
