#!/bin/sh
# Author: Bert Freudenberg. Adapted to GCompris by Bruno Coudoin.
# Purpose: Run gcompris using the old Sugar launch procedure which comes
#          pre-installed on the first mass-produced machines (Trial-3/Ship.1)
#          The new Sugar (Joyride/Update.1) uses bin/gcompris-activity instead.
#
# This version of gcompris-activity is only called under old Sugar.
# The old procedure required a dbus factory service:

exec `dirname $0`/old-gcompris-factory net.gcompris.@ACTIVITY_NAME@Activity old-gcompris-instance

