\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename gcompris.info
@settitle Documentation GCompris
@c %**end of header

@setchapternewpage odd

@ifinfo
@dircategory Games Education
@format
START-INFO-DIR-ENTRY
* gcompris: (gcompris.info).   Jeu éducatif pour les enfants de 3 à 10 ans.
END-INFO-DIR-ENTRY
@end format
Ce document est la documentation de GCompris.
Il contient à la fois un manuel utilisateur et des notes d'implémentation
utilisables pour les développeurs.

Copyright 2001 Free Software Foundation, Inc.

Permission is  granted to copy,  distribute and/or modify  this document
under the  terms of the GNU  Free Documentation License,  Version 1.1 or
any later  version published  by the Free  Software Foundation;  with no
Invariant  Sections, no Front-Cover  Texts and  no Back-Cover  Texts.  A
copy  of the  license  is included  in  the section  entitled "GNU  Free
Documentation License".
@end ifinfo

@titlepage
@sp 10
@comment The title is printed in a large font.
@center 
@titlefont{Documentation GCompris}
@author Written By Bruno Coudoin

@c The following two commands start the copyright page.
@page
@vskip 0pt plus 1filll
Copyright @copyright{} 2001 Free Software Foundation, Inc.

Permission is  granted to copy,  distribute and/or modify  this document
under the  terms of the GNU  Free Documentation License,  Version 1.1 or
any later  version published  by the Free  Software Foundation;  with no
Invariant  Sections, no Front-Cover  Texts and  no Back-Cover  Texts.  A
copy  of the  license  is included  in  the section  entitled "GNU  Free
Documentation License".
@end titlepage

@ifnottex
@node Top, Introduction, (dir), (dir)
@top Gcompris
@end ifnottex

@menu
* Introduction::		
* Manuel utilisateur::			
* Internationalisation::			
* Guide pour les développeurs::		
* GNU Free Documentation License::  
* Concept Index::		
@end menu

@node    Introduction, Manuel utilisateur, Top,      Top
@chapter Introduction
@section Pourquoi GCompris ?
Le but de GCompris est de fournir un logiciel éducatif complet et ouvert. Ce logiciel comprend un ensemble d'activités le plus varié possible couvrant les domaines de l'apprentissage de l'ordinateur, souris, clavier, les domaines d'enseignement généraux, lecture, écriture, langues vivantes, algèbre ainsi que des activités diverses comme des jeux de mémoire, de compréhension du fonctionnement d'une écluse, ...

Aujourd'hui il existe déjà beaucoup de logiciels réalisant individuellement des parties de GCompris. Malheureusement, ils sont difficiles à suivre et à maintenir et ils offrent chacun des interfaces différentes de qualités diverses.

L'objectif de GCompris est de fournir une plate forme de développement pour des activités à valeurs éducatives.

Gcompris fait partie du projet GNU.

@cindex Objectif de Gcompris

@node    Manuel utilisateur, Internationalisation, Introduction, Top
@chapter Manuel utilisateur
@section Contrôles
Tous les contrôles sont conçus pour être simples d'utilisation pour les plus jeunes. Pour cette raison, bien que GCompris utilise les librairies Gnome, il n'en suit pas les standards. GCompris est contrôlé avec une souris, il ne peut pas être utilisé sans souris ou système de pointage.

@section Zone de jeu
@cindex Interface
@cindex GUI

@subsection Fenêtre principale
Au démarrage, GCompris présente une interface graphique qui inclut :
@enumerate
@item Liste des activités
Chaque icône représente une activité. Lorsqu'on passe la souris dessus, elle est mise en surbrillance et le nom, la description, l'auteur de l'activité est affiché dans la zone 'description des activités'.
@item
@dfn{Zone de description des activités}

Zone de description des activités : Affichage d'une description de l'activité mise en surbrillance. Les descriptions sont internationalisées, c'est à dire traduites dans la langue cible sélectionnée dans GCompris (Voir @ref{Internationalisation} pour plus d'information sur l'internationalisation).

@item
Barre de contrôle :
@cindex Barre de contrôle
La barre de contrôle est toujours présente dans GCompris. Chaque icône est contextuelle, ce qui signifie quelle n'apparaît que si elle est utilisable dans le contexte courant. La barre de contrôle contient de gauche à droite :

La barre de contrôle contient de gauche à droite :
@enumerate
@item
Aide:
@cindex Icône Aide
Dans certains cas, une activité peut être trop complexe pour être décrite simplement dans la @dfn{Zone de description des activités}. Dans ce cas, cette fonction donne accès aux informations additionnelles.

@item
Niveau:
@cindex Icône Niveau
Les activités proposent en général plusieurs niveaux. Le nombre de niveaux dépend de l'activité.

@item
OK:
@cindex Icône OK
Certaines activités ne détectent pas automatiquement que l'enfant a terminé la tâche. Dans ce cas, il faut cliquer sur l'icône OK et est équivalent à utiliser la touche @key{RET} du clavier. La touche @key{RET} est un raccourci.

@item
Fin:
@cindex Icône Fin
Met fin à l'activité courante, si elle existe, ou, dans la négative, permet de sortir de GCompris. Si on clique sur cette icône au niveau du choix des activités, elle ouvrira une boite de dialogue qui demandera confirmation de la sortie de GCompris.
@cindex Quitter GCompris

@item
A propos:
@cindex Icône A propos
La boite de dialogue A propos de GCompris indique le numéro de version, les auteurs, la licence et des liens sur des ressources en ligne.
@cindex A propos de GCompris

@item
Configure:
@cindex Icône Configure
Affiche la boite de configuration de GCompris. La configuration est réalisée au niveau de GCompris lorsqu'aucune activité n'est sélectionnée, ou au niveau d'une activité si elle le permet. La configuration est persistante et est sauvée dans le répertoire home de l'utilisateur sous .gnome/GCompris. Ce fichier est un fichier texte qui peut être édité manuellement.
@cindex Configuration de GCompris

@end enumerate

@end enumerate

@subsection Lancer une activité
Tout simplement dans le menu de départ, sélectionner une activité en cliquant dessus.

@subsection Terminer une activité
Dans la barre, sélectionner le bouton 'Retour'.

@node    Internationalisation, Guide pour les développeurs, Manuel utilisateur, Top
@chapter Internationalisation
@section Ma langue est-elle supportée ?
GCompris est internationalisé et supporte déjà plusieurs langues. 
Pour savoir si la vôtre est prise en charge, vous pouvez lancer GCompris et sélectionner votre langue dans l'option de configuration. 
Si votre langue n'est pas supportée, vous pouvez réaliser la traduction vous même. Pour cela, contacter le mainteneur officiel du projet GCompris.

@section Comment traduire GCompris dans ma langue
D'abord, il faut ajouter votre nom de locale dans la variable ALL_LINGUAS du fichier configure.in.
Ensuite il faut relancer autoconf pour prendre en compte la modification.
@code{autoconf}

Puis, générer une version à jour du fichier @file{gcompris.pot} en utilisant la commande
@code{cd gcompris/po}
@code{make update-po}

Ensuite, récupérer le fichier @file{gcompris.pot}, le copier dans un fichier nommé @file{XX.po} avec XX étant le nom de votre locale, par exemple 'it' pour  italien.

Lisez le fichier généré, il contient tout le texte en Anglais trouvé dans GCompris. Il suffit ensuite de réaliser la traduction dans la zone vide située après la phrase en Anglais.

Pour vérifier la traduction, il faut l'installer avec la commande
@code{make install} au plus haut niveau.

Ensuite, envoyer la traduction au mainteneur de GCompris. Il/Elle l'inclura dans la prochaine version officielle.

@node    Guide pour les développeurs, GNU Free Documentation License, Internationalisation, Top
@chapter Guide pour les développeurs
@section Pourquoi ajouter vos activités dans GCompris
Si vous avez une idée de tableau que vous aimeriez proposer aux enfants, vous pouvez faire un nouveau projet, appelons le gIdea. Si vous commencez à partir de zéro, il vous faudra tout implémenter, menu, barre de contrôle, gestion des retours utilisateur, mécanismes d'aides, gestion du projet sur le Web, ... 
Si gIdea n'est pas un gros programme, il peut être plus simple de l'implémenter sous la forme d'une activité de GCompris. De cette façon, vous bénéficiez de l'infrastructure de GCompris et de sa constante évolution. 
Pour l'utilisateur final, il est aussi plus simple et agréable d'avoir une interface unique et consistante pour un ensemble d'activités plutôt que d'avoir à installer des programmes différents gIdea gFun g... 
Il n'est pas dans les objectifs de GCompris de devenir un langage de programmation. GCompris est implémenté en C (pour le coeur et les activités). Les activités sont chargées dynamiquement (plugins) ce qui rend possible la création et distribution de l'activité indépendamment de GCompris. 

L'implémentation de GCompris est basée sur le canvas Gnome (voir @uref{http://www.gnome.org} pour la documentation). Le canvas Gnome fournit un widget de haut niveau qui libère le programmeur de la manipulation des bitmaps lors de la réalisation d'applications graphiques. Dans l'implémentation actuelle, il n'est pas possible d'utiliser un autre ensemble de widgets. 

Certaines activités de GCompris sont conçues pour accepter de recevoir leurs jeux de données à partir d'un fichier XML. Dans ce cas, ces activités peuvent être réutilisées à condition de comprendre le format de leurs données. Pour rendre cette opération plus simple, et permettre à des non programmeurs d'utiliser ces fonctionnalités, GCompris fournira un éditeur d'activités. Il faut noter que l'activité 'shape' utilisée pour les tableaux de maîtres, par exemple, sait déjà lire et écrire ses données au format XML.

@section Comment ajouter vos activités dans GCompris

@subsection Vue d'ensemble

@image{overview, 17cm, }

@subsection GCompris API

GCompris fournit différents services aux développeurs d'activités.
Ces services sont décrits dans le fichier gcompris/gcompris.h

@itemize @bullet

@item
@code{GnomeCanvasItem *gcompris_set_background(GnomeCanvasGroup *parent, gchar *file);}

Définit l'image de fond de votre jeu. Vous pouvez trouver de l'aide dans gameutil.h pour charger l'image.

@item
@code{void gcompris_bar_set_level (GcomprisGame *gcomprisGame);}

L'utilisateur a réussi et doit faire le niveau suivant. Avant de l'appeler, @code{gcomprisGame->level} doit être mis à jour par l'activité.

@item
@code{void gcompris_bar_set_timer (guint time);}

Le 'timer' est une barre de progression qui est normalement utilisée pour informer l'utilisateur de sa progression dans l'activité. Cette valeur doit être comprise entre 0 et 'maxtimer' donnée par @code{bar_set_maxtimer()}

@item
@code{void bar_set_maxtimer (guint time);}

Établit la valeur maximale de la barre de progression. Ainsi, quand vous créez une activité, vous devez y inclure gcompris/plugin.h pour avoir accès à ces méthodes (déjà inclus dans gcompris/gcompris.h). plugin.h définit également la structure 'BoardPlugin'. C'est le noyau de GCompris. Chaque activité crée son propre 'BoardPlugin' et le renvoie à GCompris quand il est appelé par le point d'entrée get_bplugin_info() @code{BoardPlugin* *get_bplugin_info ();} La structure 'BoardPlugin' renvoyée doit contenir des 'callbacks' vers vos méthodes d'implémentation. La structure 'BoardPlugin' doit fournir des 'callbacks' vers, au moins :

@end itemize

@itemize @bullet

@item
@code{void *GcomprisStartBoard     (GcomprisBoard *gcomprisBoard);}

est appelé par GCompris quand cette activité a été demandée par l'utilisateur.

@item
@code{void *GcomprisEndBoard      (void);}

est appelé par GCompris quand l'utilisateur a cliqué sur 'Fin' dans la barre de contrôlé.

@end itemize

Éventuellement, la structure d'une activité GCompris peut contenir des 'callbacks' vers :

@itemize @bullet

@item
@code{gint *GcomprisKeyPress     (guint keyval);}

Si l'activité a besoin que l'utilisateur appuie sur des touches, elle doit fournir une méthode de 'callback'. 'keyval' (la valeur des touches ?) n'est pas filtrée et est renvoyée telle que Gnome le fait. Consulter la documentation Gnome pour comprendre comment la manipuler.

@item
@code{void *GcomprisOK           (void);}

Cette méthode est appelée quand l'utilisateur clique sur le bouton 'OK' dans la barre de contrôle. C'est une pratique censée que d'aligner le comportement des touches ENTRÉE et RETURN sur celui du bouton 'OK', mais cela ne conviendra peut-être pas à toutes les situations. Pour cette raison, la responsabilité en est laissée à l'implémentation de l'activité.

@item
@code{void *GcomprisSetLevel     (guint level);}

Est appelé avec le niveau demandé par l'utilisateur. Fournir le nombre maximal de niveaux que vous proposez dans @code{gcomprisGame->maxlevel}.
 GCompris veillera à l'appeler uniquement avec une valeur correcte.

@end itemize

@subsection Exemple de duplication d'une activité existante pour créer la vôtre

Ce qui suit décrit toutes les étapes nécessaires à l'adjonction de nouvelles activités à GCompris.

Je décris ici, à titre d'exemple, comment j'ai créé le jeu d'apprentissage de l'heure.

@enumerate
@item
Copier une activité existante (la plus proche de votre nouvelle activité).
@code{cp algebra.c clockgame.c}

@item
Éditer src/boards/Makefile.am et ajouter le fichier à la liste des librairies LTLIBRARIES, puis ajouter à la fin les entrées pour libclockgame_la_LDFLAGS, libclockgame_la_LIBADD et libclockgame_la_SOURCES. Vous pouvez consulter les exemples dans src/boards/Makefile.am afin de voir comment procéder.

@item
Dans clockgame.c, remplacer les occurrences 'algebra' par 'clockgame'.

@item
Dans clockgame.c, indiquer les informations correctes pour le nouveau jeu : 

@code{if(g_strcasecmp(gcomprisBoard->type, "clockgame")==0)}

   vous devez alors créer ou copier la description de l'activité au bon endroit :

@code{cp boards/algebra.xml boards/clockgame.xml}

  puis éditer clockgame.xml afin d'y insérer les informations correctes concernant la description de l'activité et son icône. Enregistrer le fichier de l'icône à l'endroit indiqué par clockgame.xml.

@item
Dans boards/Makefile.am ajouter votre fichier à la liste en respectant l'ordre alphanumérique. Faire de même dans po/POTFILES.in

@item
make devrait compiler le tout sans problème.

@item
Il est indispensable de faire un make install, ou l'icône ne sera pas trouvée lors de l'exécution du programme.

@item
Au lancement de GCompris, vous devriez voir la nouvelle icône et pouvoir jouer au jeu que vous avez copié. Vous pouvez maintenant coder l'activité dans clockgame.c

@item
Mettre à jour le fichier po : 
@code{cd gcompris/po}
Éditer POTFILES.in et ajouter src/clockgame.c)

@item
Ajouter maintenant la traduction dans les fichers po.
      
@item
'make' puis 'make install' compileront et installeront votre traduction.

@end enumerate

@node GNU Free Documentation License, Concept Index, Guide pour les développeurs, Top
@appendix GNU Free Documentation License

@cindex FDL, GNU Free Documentation License
@center Version 1.1, March 2000

@display
Copyright @copyright{} 2000 Free Software Foundation, Inc.
59 Temple Place, Suite 330, Boston, MA  02111-1307, USA

Everyone is permitted to copy and distribute verbatim copies
of this license document, but changing it is not allowed.
@end display

@enumerate 0
@item
PREAMBLE

The purpose of this License is to make a manual, textbook, or other
written document @dfn{free} in the sense of freedom: to assure everyone
the effective freedom to copy and redistribute it, with or without
modifying it, either commercially or noncommercially.  Secondarily,
this License preserves for the author and publisher a way to get
credit for their work, while not being considered responsible for
modifications made by others.

This License is a kind of ``copyleft'', which means that derivative
works of the document must themselves be free in the same sense.  It
complements the GNU General Public License, which is a copyleft
license designed for free software.

We have designed this License in order to use it for manuals for free
software, because free software needs free documentation: a free
program should come with manuals providing the same freedoms that the
software does.  But this License is not limited to software manuals;
it can be used for any textual work, regardless of subject matter or
whether it is published as a printed book.  We recommend this License
principally for works whose purpose is instruction or reference.

@item
APPLICABILITY AND DEFINITIONS

This License applies to any manual or other work that contains a
notice placed by the copyright holder saying it can be distributed
under the terms of this License.  The ``Document'', below, refers to any
such manual or work.  Any member of the public is a licensee, and is
addressed as ``you''.

A ``Modified Version'' of the Document means any work containing the
Document or a portion of it, either copied verbatim, or with
modifications and/or translated into another language.

A ``Secondary Section'' is a named appendix or a front-matter section of
the Document that deals exclusively with the relationship of the
publishers or authors of the Document to the Document's overall subject
(or to related matters) and contains nothing that could fall directly
within that overall subject.  (For example, if the Document is in part a
textbook of mathematics, a Secondary Section may not explain any
mathematics.)  The relationship could be a matter of historical
connection with the subject or with related matters, or of legal,
commercial, philosophical, ethical or political position regarding
them.

The ``Invariant Sections'' are certain Secondary Sections whose titles
are designated, as being those of Invariant Sections, in the notice
that says that the Document is released under this License.

The ``Cover Texts'' are certain short passages of text that are listed,
as Front-Cover Texts or Back-Cover Texts, in the notice that says that
the Document is released under this License.

A ``Transparent'' copy of the Document means a machine-readable copy,
represented in a format whose specification is available to the
general public, whose contents can be viewed and edited directly and
straightforwardly with generic text editors or (for images composed of
pixels) generic paint programs or (for drawings) some widely available
drawing editor, and that is suitable for input to text formatters or
for automatic translation to a variety of formats suitable for input
to text formatters.  A copy made in an otherwise Transparent file
format whose markup has been designed to thwart or discourage
subsequent modification by readers is not Transparent.  A copy that is
not ``Transparent'' is called ``Opaque''.

Examples of suitable formats for Transparent copies include plain
@sc{ascii} without markup, Texinfo input format, La@TeX{} input format,
@acronym{SGML} or @acronym{XML} using a publicly available
@acronym{DTD}, and standard-conforming simple @acronym{HTML} designed
for human modification.  Opaque formats include PostScript,
@acronym{PDF}, proprietary formats that can be read and edited only by
proprietary word processors, @acronym{SGML} or @acronym{XML} for which
the @acronym{DTD} and/or processing tools are not generally available,
and the machine-generated @acronym{HTML} produced by some word
processors for output purposes only.

The ``Title Page'' means, for a printed book, the title page itself,
plus such following pages as are needed to hold, legibly, the material
this License requires to appear in the title page.  For works in
formats which do not have any title page as such, ``Title Page'' means
the text near the most prominent appearance of the work's title,
preceding the beginning of the body of the text.

@item
VERBATIM COPYING

You may copy and distribute the Document in any medium, either
commercially or noncommercially, provided that this License, the
copyright notices, and the license notice saying this License applies
to the Document are reproduced in all copies, and that you add no other
conditions whatsoever to those of this License.  You may not use
technical measures to obstruct or control the reading or further
copying of the copies you make or distribute.  However, you may accept
compensation in exchange for copies.  If you distribute a large enough
number of copies you must also follow the conditions in section 3.

You may also lend copies, under the same conditions stated above, and
you may publicly display copies.

@item
COPYING IN QUANTITY

If you publish printed copies of the Document numbering more than 100,
and the Document's license notice requires Cover Texts, you must enclose
the copies in covers that carry, clearly and legibly, all these Cover
Texts: Front-Cover Texts on the front cover, and Back-Cover Texts on
the back cover.  Both covers must also clearly and legibly identify
you as the publisher of these copies.  The front cover must present
the full title with all words of the title equally prominent and
visible.  You may add other material on the covers in addition.
Copying with changes limited to the covers, as long as they preserve
the title of the Document and satisfy these conditions, can be treated
as verbatim copying in other respects.

If the required texts for either cover are too voluminous to fit
legibly, you should put the first ones listed (as many as fit
reasonably) on the actual cover, and continue the rest onto adjacent
pages.

If you publish or distribute Opaque copies of the Document numbering
more than 100, you must either include a machine-readable Transparent
copy along with each Opaque copy, or state in or with each Opaque copy
a publicly-accessible computer-network location containing a complete
Transparent copy of the Document, free of added material, which the
general network-using public has access to download anonymously at no
charge using public-standard network protocols.  If you use the latter
option, you must take reasonably prudent steps, when you begin
distribution of Opaque copies in quantity, to ensure that this
Transparent copy will remain thus accessible at the stated location
until at least one year after the last time you distribute an Opaque
copy (directly or through your agents or retailers) of that edition to
the public.

It is requested, but not required, that you contact the authors of the
Document well before redistributing any large number of copies, to give
them a chance to provide you with an updated version of the Document.

@item
MODIFICATIONS

You may copy and distribute a Modified Version of the Document under
the conditions of sections 2 and 3 above, provided that you release
the Modified Version under precisely this License, with the Modified
Version filling the role of the Document, thus licensing distribution
and modification of the Modified Version to whoever possesses a copy
of it.  In addition, you must do these things in the Modified Version:

@enumerate A
@item
Use in the Title Page (and on the covers, if any) a title distinct
from that of the Document, and from those of previous versions
(which should, if there were any, be listed in the History section
of the Document).  You may use the same title as a previous version
if the original publisher of that version gives permission.

@item
List on the Title Page, as authors, one or more persons or entities
responsible for authorship of the modifications in the Modified
Version, together with at least five of the principal authors of the
Document (all of its principal authors, if it has less than five).

@item
State on the Title page the name of the publisher of the
Modified Version, as the publisher.

@item
Preserve all the copyright notices of the Document.

@item
Add an appropriate copyright notice for your modifications
adjacent to the other copyright notices.

@item
Include, immediately after the copyright notices, a license notice
giving the public permission to use the Modified Version under the
terms of this License, in the form shown in the Addendum below.

@item
Preserve in that license notice the full lists of Invariant Sections
and required Cover Texts given in the Document's license notice.

@item
Include an unaltered copy of this License.

@item
Preserve the section entitled ``History'', and its title, and add to
it an item stating at least the title, year, new authors, and
publisher of the Modified Version as given on the Title Page.  If
there is no section entitled ``History'' in the Document, create one
stating the title, year, authors, and publisher of the Document as
given on its Title Page, then add an item describing the Modified
Version as stated in the previous sentence.

@item
Preserve the network location, if any, given in the Document for
public access to a Transparent copy of the Document, and likewise
the network locations given in the Document for previous versions
it was based on.  These may be placed in the ``History'' section.
You may omit a network location for a work that was published at
least four years before the Document itself, or if the original
publisher of the version it refers to gives permission.

@item
In any section entitled ``Acknowledgments'' or ``Dedications'',
preserve the section's title, and preserve in the section all the
substance and tone of each of the contributor acknowledgments
and/or dedications given therein.

@item
Preserve all the Invariant Sections of the Document,
unaltered in their text and in their titles.  Section numbers
or the equivalent are not considered part of the section titles.

@item
Delete any section entitled ``Endorsements''.  Such a section
may not be included in the Modified Version.

@item
Do not retitle any existing section as ``Endorsements''
or to conflict in title with any Invariant Section.
@end enumerate

If the Modified Version includes new front-matter sections or
appendices that qualify as Secondary Sections and contain no material
copied from the Document, you may at your option designate some or all
of these sections as invariant.  To do this, add their titles to the
list of Invariant Sections in the Modified Version's license notice.
These titles must be distinct from any other section titles.

You may add a section entitled ``Endorsements'', provided it contains
nothing but endorsements of your Modified Version by various
parties---for example, statements of peer review or that the text has
been approved by an organization as the authoritative definition of a
standard.

You may add a passage of up to five words as a Front-Cover Text, and a
passage of up to 25 words as a Back-Cover Text, to the end of the list
of Cover Texts in the Modified Version.  Only one passage of
Front-Cover Text and one of Back-Cover Text may be added by (or
through arrangements made by) any one entity.  If the Document already
includes a cover text for the same cover, previously added by you or
by arrangement made by the same entity you are acting on behalf of,
you may not add another; but you may replace the old one, on explicit
permission from the previous publisher that added the old one.

The author(s) and publisher(s) of the Document do not by this License
give permission to use their names for publicity for or to assert or
imply endorsement of any Modified Version.

@item
COMBINING DOCUMENTS

You may combine the Document with other documents released under this
License, under the terms defined in section 4 above for modified
versions, provided that you include in the combination all of the
Invariant Sections of all of the original documents, unmodified, and
list them all as Invariant Sections of your combined work in its
license notice.

The combined work need only contain one copy of this License, and
multiple identical Invariant Sections may be replaced with a single
copy.  If there are multiple Invariant Sections with the same name but
different contents, make the title of each such section unique by
adding at the end of it, in parentheses, the name of the original
author or publisher of that section if known, or else a unique number.
Make the same adjustment to the section titles in the list of
Invariant Sections in the license notice of the combined work.

In the combination, you must combine any sections entitled ``History''
in the various original documents, forming one section entitled
``History''; likewise combine any sections entitled ``Acknowledgments'',
and any sections entitled ``Dedications''.  You must delete all sections
entitled ``Endorsements.''

@item
COLLECTIONS OF DOCUMENTS

You may make a collection consisting of the Document and other documents
released under this License, and replace the individual copies of this
License in the various documents with a single copy that is included in
the collection, provided that you follow the rules of this License for
verbatim copying of each of the documents in all other respects.

You may extract a single document from such a collection, and distribute
it individually under this License, provided you insert a copy of this
License into the extracted document, and follow this License in all
other respects regarding verbatim copying of that document.

@item
AGGREGATION WITH INDEPENDENT WORKS

A compilation of the Document or its derivatives with other separate
and independent documents or works, in or on a volume of a storage or
distribution medium, does not as a whole count as a Modified Version
of the Document, provided no compilation copyright is claimed for the
compilation.  Such a compilation is called an ``aggregate'', and this
License does not apply to the other self-contained works thus compiled
with the Document, on account of their being thus compiled, if they
are not themselves derivative works of the Document.

If the Cover Text requirement of section 3 is applicable to these
copies of the Document, then if the Document is less than one quarter
of the entire aggregate, the Document's Cover Texts may be placed on
covers that surround only the Document within the aggregate.
Otherwise they must appear on covers around the whole aggregate.

@item
TRANSLATION

Translation is considered a kind of modification, so you may
distribute translations of the Document under the terms of section 4.
Replacing Invariant Sections with translations requires special
permission from their copyright holders, but you may include
translations of some or all Invariant Sections in addition to the
original versions of these Invariant Sections.  You may include a
translation of this License provided that you also include the
original English version of this License.  In case of a disagreement
between the translation and the original English version of this
License, the original English version will prevail.

@item
TERMINATION

You may not copy, modify, sublicense, or distribute the Document except
as expressly provided for under this License.  Any other attempt to
copy, modify, sublicense or distribute the Document is void, and will
automatically terminate your rights under this License.  However,
parties who have received copies, or rights, from you under this
License will not have their licenses terminated so long as such
parties remain in full compliance.

@item
FUTURE REVISIONS OF THIS LICENSE

The Free Software Foundation may publish new, revised versions
of the GNU Free Documentation License from time to time.  Such new
versions will be similar in spirit to the present version, but may
differ in detail to address new problems or concerns.  See
@uref{http://www.gnu.org/copyleft/}.

Each version of the License is given a distinguishing version number.
If the Document specifies that a particular numbered version of this
License ``or any later version'' applies to it, you have the option of
following the terms and conditions either of that specified version or
of any later version that has been published (not as a draft) by the
Free Software Foundation.  If the Document does not specify a version
number of this License, you may choose any version ever published (not
as a draft) by the Free Software Foundation.
@end enumerate

@page
@appendixsubsec ADDENDUM: How to use this License for your documents

To use this License in a document you have written, include a copy of
the License in the document and put the following copyright and
license notices just after the title page:

@smallexample
@group
  Copyright (C)  @var{year}  @var{your name}.
  Permission is granted to copy, distribute and/or modify this document
  under the terms of the GNU Free Documentation License, Version 1.1
  or any later version published by the Free Software Foundation;
  with the Invariant Sections being @var{list their titles}, with the
  Front-Cover Texts being @var{list}, and with the Back-Cover Texts being @var{list}.
  A copy of the license is included in the section entitled ``GNU
  Free Documentation License''.
@end group
@end smallexample

If you have no Invariant Sections, write ``with no Invariant Sections''
instead of saying which ones are invariant.  If you have no
Front-Cover Texts, write ``no Front-Cover Texts'' instead of
``Front-Cover Texts being @var{list}''; likewise for Back-Cover Texts.

If your document contains nontrivial examples of program code, we
recommend releasing these examples in parallel under your choice of
free software license, such as the GNU General Public License,
to permit their use in free software.

@node     Concept Index,  , GNU Free Documentation License, Top
@comment      node-name, next,       previous, up
@unnumbered Concept Index
     
@printindex cp

@contents
@bye